### ISSUE TITLE
Text bug

### ISSUE THREAD

**Issue by mhdsmd** [knrt10/kubernetes-basicLearning#16]
Thanks for the good article!
In the section [deleting-all-pods-in-namespace-while-keeping-the-namespace ](https://github.com/knrt10/kubernetes-basicLearning#deleting-all-pods-in-namespace-while-keeping-the-namespace )you have a mistake in a word in the first command:
`kubeclt delete po --all`
You used `kubeclt` instead of `kubectl`.

**Comment by knrt10** [comment]
@mhdsmd thank you for opening this issue, fixed via https://github.com/knrt10/kubernetes-basicLearning/commit/bd37fae013e9a1db3cd2dfdac0dc5c1e74a7ec0c
