### ISSUE TITLE
Seriously good Kubernetes Tutorial

### ISSUE THREAD

**Issue by ngrok-patrick** [knrt10/kubernetes-basicLearning#19]
There are so many Kubernetes tutorials, this one is **Great** ! Seriously, in `10 minutes` you Fly through many examples, and really get a hang of Kubernetes.

Thanks for taking the time to create this

# Thank You !

**Comment by knrt10** [comment]
Thank you @ngrok-patrick for your kind comments. Closing this issue since unrelated to the code.
