### ISSUE TITLE
Suggestion: Adding what's kubernetes?

### ISSUE THREAD

**Issue by yasinaydin** [knrt10/kubernetes-basicLearning#4]
Docker part has a "What's Docker" section, but Kubernetes part doesn't. It might be good idea to add that, too.

**Comment by knrt10** [comment]
That is a good idea @yasinaydin. Thank you for your suggestions.

**Comment by yasinaydin** [comment]
Sure thing. I'd add it myself, but I don't know enough about k8s to write a such thing :D

**Comment by knrt10** [comment]
No problem, if anyone does not take it up. I will add it
