### ISSUE TITLE
issues with `kubectl run kubia`

### ISSUE THREAD

**Issue by aae42** [knrt10/kubernetes-basicLearning#8]
thanks so much for the document, going through it to myself and noticed an issue here...

the step where you first deploy your image:
`kubectl run kubia --image=aae42/kubia --port=8080 --generator=run/v1`
i get an error:
`Flag --generator has been deprecated, has no effect and will be removed in the future.`
you can ignore this, but as soon as you try to do the next step, you get an error:
`Error from server (NotFound): replicationcontrollers "kubia" not found`
when trying to do the load balancer

using minikube v.1.11.0 and kubernetes v1.18.3

**Comment by knrt10** [comment]
@aae42 can you share the output of `kubeclt get rc ---all-namespaces`

**Comment by aae42** [comment]
thanks for your quick response!
```
> kubectl get rc --all-namespaces
No resources found
```

**Comment by aae42** [comment]
ah, interestingly enough, in `kind` it seems to work just fine... `kubectl get rc --all-namespaces` lists a namespace named `kubia`

**Comment by knrt10** [comment]
I hope this solves the issue, I will be updating the readme very soon regarding deprecated generator. If the issue is not fixed, please feel free to reopen the issue

**Comment by nextonr** [comment]
Guess you are reading k8s in action, the generator is no longer used in your k8s version, try:

kubectl expose pod kubia --type=LoadBalancer --name kubia-http
