### ISSUE TITLE
Need update: Kubernetes 1.18 broke “kubectl run”

### ISSUE THREAD

**Issue by alexmitelman** [knrt10/kubernetes-basicLearning#9]
This command no longer creates ReplicationController as of 1.18:
https://github.com/knrt10/kubernetes-basicLearning/blob/master/readme.md#deploying-your-node-app
`kubectl run kubia --image=knrt10/kubia --port=8080 --generator=run/v1`
returns `Flag --generator has been deprecated, has no effect and will be removed in the future.`

**Comment by knrt10** [comment]
Thank you for the issue @alexmitelman, can you please make a PR for it?

**Comment by alenzen** [comment]
I just opened a pull request (#15) for this issue.

Thank you, @knrt10.

**Comment by knrt10** [comment]
closed via #15
